name: Deploy to GitHub Pages and Build WordPress Plugin

on:
  push:
    branches: ['master']  # Using master instead of main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build WordPress Plugin
        run: npm run build:wp
      - name: Build
        run: npm run build
      - name: Copy public files
        run: |
          cp -r public/* dist/ || true
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Upload WordPress Plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: wordpress-plugin
          path: dist-wp/energy-calculator.zip